// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Interpreter.Specs.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class IsPrimeFeature : object, global::Xunit.IClassFixture<IsPrimeFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en"), "Features", "IsPrime", "  Программа проверяет, является ли число простым", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "IsPrime.feature"
#line hidden
        
        public IsPrimeFeature(IsPrimeFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/IsPrime.feature.ndjson", 8);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Число меньше двух не является простым")]
        [global::Xunit.TraitAttribute("FeatureTitle", "IsPrime")]
        [global::Xunit.TraitAttribute("Description", "Число меньше двух не является простым")]
        public async global::System.Threading.Tasks.Task ЧислоМеньшеДвухНеЯвляетсяПростым()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Число меньше двух не является простым", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
    await testRunner.GivenAsync("я написал программу:", @"// Начало программы
bello!

// Функция is_prime: возвращает 1.0, если число простое, иначе 0.0
boss is_prime Papaya (n) oca!
    // Числа меньше 2 не являются простыми
    bi-do (n la 2.0) oca!
        tank yu 0.0 naidu!
    stopa
    // Число 2 — простое
    bi-do (n con 2.0) oca!
        tank yu 1.0 naidu!
    stopa

    // Начинаем проверку делителей с числа 2
    poop i Papaya naidu!
    i lumai 2.0 naidu!

    // Пока i * i <= n (то есть i <= sqrt(n))
    kemari (i dibotada i lacon n) oca!
        // Если n делится на i без остатка — число составное
        bi-do (n pado i con 0.0) oca!
            tank yu 0.0 naidu!  // Не простое
        stopa
        // Увеличиваем i на 1
        i lumai i melomo 1.0 naidu!
    stopa

    // Если ни один делитель не найден — число простое
    tank yu 1.0 naidu!
stopa

// Считываем число с клавиатуры
poop n Papaya naidu!
guoleila (n) naidu!
// Выводим 1.0 (простое) или 0.0 (составное)
tulalilloo ti amo (is_prime (n)) naidu!", ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 45
    await testRunner.WhenAsync("я ввожу в консоли:", "1", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 49
    await testRunner.ThenAsync("я увижу в консоли:", "0", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Число два является простым")]
        [global::Xunit.TraitAttribute("FeatureTitle", "IsPrime")]
        [global::Xunit.TraitAttribute("Description", "Число два является простым")]
        public async global::System.Threading.Tasks.Task ЧислоДваЯвляетсяПростым()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Число два является простым", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 54
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 55
    await testRunner.GivenAsync("я написал программу:", @"// Начало программы
bello!

// Функция is_prime: возвращает 1.0, если число простое, иначе 0.0
boss is_prime Papaya (n) oca!
    // Числа меньше 2 не являются простыми
    bi-do (n la 2.0) oca!
        tank yu 0.0 naidu!
    stopa
    // Число 2 — простое
    bi-do (n con 2.0) oca!
        tank yu 1.0 naidu!
    stopa

    // Начинаем проверку делителей с числа 2
    poop i Papaya naidu!
    i lumai 2.0 naidu!

    // Пока i * i <= n (то есть i <= sqrt(n))
    kemari (i dibotada i lacon n) oca!
        // Если n делится на i без остатка — число составное
        bi-do (n pado i con 0.0) oca!
            tank yu 0.0 naidu!  // Не простое
        stopa
        // Увеличиваем i на 1
        i lumai i melomo 1.0 naidu!
    stopa

    // Если ни один делитель не найден — число простое
    tank yu 1.0 naidu!
stopa

// Считываем число с клавиатуры
poop n Papaya naidu!
guoleila (n) naidu!
// Выводим 1.0 (простое) или 0.0 (составное)
tulalilloo ti amo (is_prime (n)) naidu!", ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 95
    await testRunner.WhenAsync("я ввожу в консоли:", "2", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 99
    await testRunner.ThenAsync("я увижу в консоли:", "1", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Простое число три")]
        [global::Xunit.TraitAttribute("FeatureTitle", "IsPrime")]
        [global::Xunit.TraitAttribute("Description", "Простое число три")]
        public async global::System.Threading.Tasks.Task ПростоеЧислоТри()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Простое число три", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 104
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 105
    await testRunner.GivenAsync("я написал программу:", @"// Начало программы
bello!

// Функция is_prime: возвращает 1.0, если число простое, иначе 0.0
boss is_prime Papaya (n) oca!
    // Числа меньше 2 не являются простыми
    bi-do (n la 2.0) oca!
        tank yu 0.0 naidu!
    stopa
    // Число 2 — простое
    bi-do (n con 2.0) oca!
        tank yu 1.0 naidu!
    stopa

    // Начинаем проверку делителей с числа 2
    poop i Papaya naidu!
    i lumai 2.0 naidu!

    // Пока i * i <= n (то есть i <= sqrt(n))
    kemari (i dibotada i lacon n) oca!
        // Если n делится на i без остатка — число составное
        bi-do (n pado i con 0.0) oca!
            tank yu 0.0 naidu!  // Не простое
        stopa
        // Увеличиваем i на 1
        i lumai i melomo 1.0 naidu!
    stopa

    // Если ни один делитель не найден — число простое
    tank yu 1.0 naidu!
stopa

// Считываем число с клавиатуры
poop n Papaya naidu!
guoleila (n) naidu!
// Выводим 1.0 (простое) или 0.0 (составное)
tulalilloo ti amo (is_prime (n)) naidu!", ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 145
    await testRunner.WhenAsync("я ввожу в консоли:", "3", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 149
    await testRunner.ThenAsync("я увижу в консоли:", "1", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Составное число четыре")]
        [global::Xunit.TraitAttribute("FeatureTitle", "IsPrime")]
        [global::Xunit.TraitAttribute("Description", "Составное число четыре")]
        public async global::System.Threading.Tasks.Task СоставноеЧислоЧетыре()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Составное число четыре", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 154
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 155
    await testRunner.GivenAsync("я написал программу:", @"// Начало программы
bello!

// Функция is_prime: возвращает 1.0, если число простое, иначе 0.0
boss is_prime Papaya (n) oca!
    // Числа меньше 2 не являются простыми
    bi-do (n la 2.0) oca!
        tank yu 0.0 naidu!
    stopa
    // Число 2 — простое
    bi-do (n con 2.0) oca!
        tank yu 1.0 naidu!
    stopa

    // Начинаем проверку делителей с числа 2
    poop i Papaya naidu!
    i lumai 2.0 naidu!

    // Пока i * i <= n (то есть i <= sqrt(n))
    kemari (i dibotada i lacon n) oca!
        // Если n делится на i без остатка — число составное
        bi-do (n pado i con 0.0) oca!
            tank yu 0.0 naidu!  // Не простое
        stopa
        // Увеличиваем i на 1
        i lumai i melomo 1.0 naidu!
    stopa

    // Если ни один делитель не найден — число простое
    tank yu 1.0 naidu!
stopa

// Считываем число с клавиатуры
poop n Papaya naidu!
guoleila (n) naidu!
// Выводим 1.0 (простое) или 0.0 (составное)
tulalilloo ti amo (is_prime (n)) naidu!", ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 195
    await testRunner.WhenAsync("я ввожу в консоли:", "4", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 199
    await testRunner.ThenAsync("я увижу в консоли:", "0", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Простое число семнадцать")]
        [global::Xunit.TraitAttribute("FeatureTitle", "IsPrime")]
        [global::Xunit.TraitAttribute("Description", "Простое число семнадцать")]
        public async global::System.Threading.Tasks.Task ПростоеЧислоСемнадцать()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Простое число семнадцать", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 204
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 205
    await testRunner.GivenAsync("я написал программу:", @"// Начало программы
bello!

// Функция is_prime: возвращает 1.0, если число простое, иначе 0.0
boss is_prime Papaya (n) oca!
    // Числа меньше 2 не являются простыми
    bi-do (n la 2.0) oca!
        tank yu 0.0 naidu!
    stopa
    // Число 2 — простое
    bi-do (n con 2.0) oca!
        tank yu 1.0 naidu!
    stopa

    // Начинаем проверку делителей с числа 2
    poop i Papaya naidu!
    i lumai 2.0 naidu!

    // Пока i * i <= n (то есть i <= sqrt(n))
    kemari (i dibotada i lacon n) oca!
        // Если n делится на i без остатка — число составное
        bi-do (n pado i con 0.0) oca!
            tank yu 0.0 naidu!  // Не простое
        stopa
        // Увеличиваем i на 1
        i lumai i melomo 1.0 naidu!
    stopa

    // Если ни один делитель не найден — число простое
    tank yu 1.0 naidu!
stopa

// Считываем число с клавиатуры
poop n Papaya naidu!
guoleila (n) naidu!
// Выводим 1.0 (простое) или 0.0 (составное)
tulalilloo ti amo (is_prime (n)) naidu!", ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 245
    await testRunner.WhenAsync("я ввожу в консоли:", "17", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 249
    await testRunner.ThenAsync("я увижу в консоли:", "1", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Составное число двадцать пять")]
        [global::Xunit.TraitAttribute("FeatureTitle", "IsPrime")]
        [global::Xunit.TraitAttribute("Description", "Составное число двадцать пять")]
        public async global::System.Threading.Tasks.Task СоставноеЧислоДвадцатьПять()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Составное число двадцать пять", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 254
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 255
    await testRunner.GivenAsync("я написал программу:", @"// Начало программы
bello!

// Функция is_prime: возвращает 1.0, если число простое, иначе 0.0
boss is_prime Papaya (n) oca!
    // Числа меньше 2 не являются простыми
    bi-do (n la 2.0) oca!
        tank yu 0.0 naidu!
    stopa
    // Число 2 — простое
    bi-do (n con 2.0) oca!
        tank yu 1.0 naidu!
    stopa

    // Начинаем проверку делителей с числа 2
    poop i Papaya naidu!
    i lumai 2.0 naidu!

    // Пока i * i <= n (то есть i <= sqrt(n))
    kemari (i dibotada i lacon n) oca!
        // Если n делится на i без остатка — число составное
        bi-do (n pado i con 0.0) oca!
            tank yu 0.0 naidu!  // Не простое
        stopa
        // Увеличиваем i на 1
        i lumai i melomo 1.0 naidu!
    stopa

    // Если ни один делитель не найден — число простое
    tank yu 1.0 naidu!
stopa

// Считываем число с клавиатуры
poop n Papaya naidu!
guoleila (n) naidu!
// Выводим 1.0 (простое) или 0.0 (составное)
tulalilloo ti amo (is_prime (n)) naidu!", ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 295
    await testRunner.WhenAsync("я ввожу в консоли:", "25", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 299
    await testRunner.ThenAsync("я увижу в консоли:", "0", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await IsPrimeFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await IsPrimeFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
