// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Interpreter.Specs.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class PowFeature : object, global::Xunit.IClassFixture<PowFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en"), "Features", "Pow", "  Программа возводит число в целую неотрицательную степень", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Pow.feature"
#line hidden
        
        public PowFeature(PowFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Pow.feature.ndjson", 7);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Возведение в нулевую степень")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Pow")]
        [global::Xunit.TraitAttribute("Description", "Возведение в нулевую степень")]
        public async global::System.Threading.Tasks.Task ВозведениеВНулевуюСтепень()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Возведение в нулевую степень", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
    await testRunner.GivenAsync("я написал программу:", @"// Начало программы
bello!

// Функция pow: возводит base в целую неотрицательную степень exp
boss pow Papaya (base, exp) oca!
    // Начальное значение результата — 1
    poop result Papaya naidu!
    result lumai 1.0 naidu!

    // Счётчик итераций: начинаем с 0
    poop i Papaya naidu!
    i lumai 0.0 naidu!

    // Повторяем exp раз: умножаем result на base
    kemari (i la exp) oca!
        result lumai result dibotada base naidu!  // result = result * base
        i lumai i melomo 1.0 naidu!               // i = i + 1
    stopa

    // Возвращаем итоговый результат
    tank yu result naidu!
stopa

// Считываем основание степени
poop a Papaya naidu!
guoleila (a) naidu!
// Считываем показатель степени
poop b Papaya naidu!
guoleila (b) naidu!
// Выводим результат: a^b
tulalilloo ti amo (pow (a, b)) naidu!", ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 39
    await testRunner.WhenAsync("я ввожу в консоли:", "5\r\n0", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 44
    await testRunner.ThenAsync("я увижу в консоли:", "1", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Возведение в первую степень")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Pow")]
        [global::Xunit.TraitAttribute("Description", "Возведение в первую степень")]
        public async global::System.Threading.Tasks.Task ВозведениеВПервуюСтепень()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Возведение в первую степень", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 49
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 50
    await testRunner.GivenAsync("я написал программу:", @"// Начало программы
bello!

// Функция pow: возводит base в целую неотрицательную степень exp
boss pow Papaya (base, exp) oca!
    // Начальное значение результата — 1
    poop result Papaya naidu!
    result lumai 1.0 naidu!

    // Счётчик итераций: начинаем с 0
    poop i Papaya naidu!
    i lumai 0.0 naidu!

    // Повторяем exp раз: умножаем result на base
    kemari (i la exp) oca!
        result lumai result dibotada base naidu!  // result = result * base
        i lumai i melomo 1.0 naidu!               // i = i + 1
    stopa

    // Возвращаем итоговый результат
    tank yu result naidu!
stopa

// Считываем основание степени
poop a Papaya naidu!
guoleila (a) naidu!
// Считываем показатель степени
poop b Papaya naidu!
guoleila (b) naidu!
// Выводим результат: a^b
tulalilloo ti amo (pow (a, b)) naidu!", ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 84
    await testRunner.WhenAsync("я ввожу в консоли:", "7\r\n1", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 89
    await testRunner.ThenAsync("я увижу в консоли:", "7", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Возведение два в степень три")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Pow")]
        [global::Xunit.TraitAttribute("Description", "Возведение два в степень три")]
        public async global::System.Threading.Tasks.Task ВозведениеДваВСтепеньТри()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Возведение два в степень три", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 94
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 95
    await testRunner.GivenAsync("я написал программу:", @"// Начало программы
bello!

// Функция pow: возводит base в целую неотрицательную степень exp
boss pow Papaya (base, exp) oca!
    // Начальное значение результата — 1
    poop result Papaya naidu!
    result lumai 1.0 naidu!

    // Счётчик итераций: начинаем с 0
    poop i Papaya naidu!
    i lumai 0.0 naidu!

    // Повторяем exp раз: умножаем result на base
    kemari (i la exp) oca!
        result lumai result dibotada base naidu!  // result = result * base
        i lumai i melomo 1.0 naidu!               // i = i + 1
    stopa

    // Возвращаем итоговый результат
    tank yu result naidu!
stopa

// Считываем основание степени
poop a Papaya naidu!
guoleila (a) naidu!
// Считываем показатель степени
poop b Papaya naidu!
guoleila (b) naidu!
// Выводим результат: a^b
tulalilloo ti amo (pow (a, b)) naidu!", ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 129
    await testRunner.WhenAsync("я ввожу в консоли:", "2\r\n3", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 134
    await testRunner.ThenAsync("я увижу в консоли:", "8", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Возведение три в степень четыре")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Pow")]
        [global::Xunit.TraitAttribute("Description", "Возведение три в степень четыре")]
        public async global::System.Threading.Tasks.Task ВозведениеТриВСтепеньЧетыре()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Возведение три в степень четыре", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 139
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 140
    await testRunner.GivenAsync("я написал программу:", @"// Начало программы
bello!

// Функция pow: возводит base в целую неотрицательную степень exp
boss pow Papaya (base, exp) oca!
    // Начальное значение результата — 1
    poop result Papaya naidu!
    result lumai 1.0 naidu!

    // Счётчик итераций: начинаем с 0
    poop i Papaya naidu!
    i lumai 0.0 naidu!

    // Повторяем exp раз: умножаем result на base
    kemari (i la exp) oca!
        result lumai result dibotada base naidu!  // result = result * base
        i lumai i melomo 1.0 naidu!               // i = i + 1
    stopa

    // Возвращаем итоговый результат
    tank yu result naidu!
stopa

// Считываем основание степени
poop a Papaya naidu!
guoleila (a) naidu!
// Считываем показатель степени
poop b Papaya naidu!
guoleila (b) naidu!
// Выводим результат: a^b
tulalilloo ti amo (pow (a, b)) naidu!", ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 174
    await testRunner.WhenAsync("я ввожу в консоли:", "3\r\n4", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 179
    await testRunner.ThenAsync("я увижу в консоли:", "81", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Возведение пять в степень три")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Pow")]
        [global::Xunit.TraitAttribute("Description", "Возведение пять в степень три")]
        public async global::System.Threading.Tasks.Task ВозведениеПятьВСтепеньТри()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Возведение пять в степень три", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 184
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 185
    await testRunner.GivenAsync("я написал программу:", @"// Начало программы
bello!

// Функция pow: возводит base в целую неотрицательную степень exp
boss pow Papaya (base, exp) oca!
    // Начальное значение результата — 1
    poop result Papaya naidu!
    result lumai 1.0 naidu!

    // Счётчик итераций: начинаем с 0
    poop i Papaya naidu!
    i lumai 0.0 naidu!

    // Повторяем exp раз: умножаем result на base
    kemari (i la exp) oca!
        result lumai result dibotada base naidu!  // result = result * base
        i lumai i melomo 1.0 naidu!               // i = i + 1
    stopa

    // Возвращаем итоговый результат
    tank yu result naidu!
stopa

// Считываем основание степени
poop a Papaya naidu!
guoleila (a) naidu!
// Считываем показатель степени
poop b Papaya naidu!
guoleila (b) naidu!
// Выводим результат: a^b
tulalilloo ti amo (pow (a, b)) naidu!", ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 219
    await testRunner.WhenAsync("я ввожу в консоли:", "5\r\n3", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 224
    await testRunner.ThenAsync("я увижу в консоли:", "125", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await PowFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await PowFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
